apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: mysql
  name: mysql
  namespace: mediawiki
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: mediawiki123
        - name: MYSQL_DATABASE
          value: mediawiki
        - name: MYSQL_USER
          value: mediawiki
        - name: MYSQL_PASSWORD
          value: mediawiki123
        args:
        - --basedir=/var/database/mysql
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        name: mysql
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/database
          name: database
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: pvc-database
